name: camo_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
# Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.6
  smooth_page_indicator: ^1.1.0
  
# Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

#Satate Management
  get: ^4.6.6
  get_storage: ^2.1.1
  
#Product Specific  
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/logos/
     - assets/icons/
     - assets/images/user/
     - assets/images/on_boarding_images/
     - assets/images/animations/
     - assets/icons/categories/
     - assets/images/banners/
     - assets/images/products/
     - assets/icons/payment/
     - assets/images/reviews/
     
  
  fonts:
     - family: Poppins
       fonts:
          - asset: assets\fonts\Poppins-Light.ttf
            weight: 300
          - asset: assets\fonts\Poppins-Regular.ttf
            weight: 400
          - asset: assets\fonts\Poppins-Italic.ttf
            style: italic
          - asset: assets\fonts\Poppins-Medium.ttf
            weight: 500
          - asset: assets\fonts\Poppins-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets\fonts\Poppins-SemiBold.ttf
            weight: 600
          - asset: assets\fonts\Poppins-Bold.ttf
            weight: 800
