// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_quorvkE7T_MRVcIfTVQiEc90Q4meo28',
    appId: '1:652780170642:web:1e63587c84c30d2c4ca54b',
    messagingSenderId: '652780170642',
    projectId: 'camo-app-c04ed',
    authDomain: 'camo-app-c04ed.firebaseapp.com',
    storageBucket: 'camo-app-c04ed.appspot.com',
    measurementId: 'G-LGVXS9T70S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuAUcxzUI2wlniKEF5sMeTP5ojx3ogOo',
    appId: '1:652780170642:android:2f5b9e531341ce924ca54b',
    messagingSenderId: '652780170642',
    projectId: 'camo-app-c04ed',
    storageBucket: 'camo-app-c04ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMIOlS0429vC4guu2jKjNLl6GGdKGX7OI',
    appId: '1:652780170642:ios:937eec82b2c9fc784ca54b',
    messagingSenderId: '652780170642',
    projectId: 'camo-app-c04ed',
    storageBucket: 'camo-app-c04ed.appspot.com',
    androidClientId: '652780170642-gihmcbuqb7od7t4b658nqputlk1gopsr.apps.googleusercontent.com',
    iosClientId: '652780170642-80mh13p1c63soqb0dfo53atnmms3g1k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.camo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMIOlS0429vC4guu2jKjNLl6GGdKGX7OI',
    appId: '1:652780170642:ios:114363872dd876424ca54b',
    messagingSenderId: '652780170642',
    projectId: 'camo-app-c04ed',
    storageBucket: 'camo-app-c04ed.appspot.com',
    androidClientId: '652780170642-gihmcbuqb7od7t4b658nqputlk1gopsr.apps.googleusercontent.com',
    iosClientId: '652780170642-9v1d4d1dc3nksgpkr3sha868d4bl34qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.camo.RunnerTests',
  );
}
